[
    {
      "name": "Ibuprofeno",
      "description": "Antiinflamatorio no esteroideo (AINE) utilizado para reducir la fiebre y aliviar el dolor leve a moderado.",
      "type": "Analgésico",
      "presentation": "Tabletas",
      "unit": "mg",
      "dosage": "400mg cada 6 horas",
      "composition": ["Ibuprofeno"],
      "price": 15.0,
      "stock": 80,
      "manufacturer": "Advil",
      "expirationDate": "2026-12-31T00:00:00.000+00:00",
      "prescriptionRequired": false,
      "administrationRoute": "Oral",
      "sideEffects": ["Náuseas", "Mareos", "Acidez estomacal"],
      "indications": ["Dolor", "Fiebre"],
      "contraindications": ["Úlceras gástricas"],
      "imageUrl": "images/ibuprofeno.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Amoxicilina",
      "description": "Antibiótico utilizado para tratar infecciones bacterianas como bronquitis, neumonía y amigdalitis.",
      "type": "Antibiótico",
      "presentation": "Cápsulas",
      "unit": "mg",
      "dosage": "500mg cada 8 horas",
      "composition": ["Amoxicilina trihidratada"],
      "price": 28.0,
      "stock": 60,
      "manufacturer": "Sandoz",
      "expirationDate": "2026-08-15T00:00:00.000+00:00",
      "prescriptionRequired": true,
      "administrationRoute": "Oral",
      "sideEffects": ["Diarrea", "Erupción cutánea", "Náuseas"],
      "indications": ["Infecciones respiratorias", "Infecciones urinarias"],
      "contraindications": ["Alergia a penicilinas"],
      "imageUrl": "images/amoxicilina.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Loratadina",
      "description": "Antihistamínico utilizado para aliviar los síntomas de alergias como estornudos y picazón.",
      "type": "Antihistamínico",
      "presentation": "Tabletas",
      "unit": "mg",
      "dosage": "10mg una vez al día",
      "composition": ["Loratadina"],
      "price": 12.0,
      "stock": 100,
      "manufacturer": "Genfar",
      "expirationDate": "2027-01-20T00:00:00.000+00:00",
      "prescriptionRequired": false,
      "administrationRoute": "Oral",
      "sideEffects": ["Somnolencia", "Dolor de cabeza"],
      "indications": ["Rinitis alérgica", "Urticaria"],
      "contraindications": ["Enfermedad hepática severa"],
      "imageUrl": "images/loratadina.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Metformina",
      "description": "Medicamento oral utilizado para controlar los niveles de azúcar en la sangre en personas con diabetes tipo 2.",
      "type": "Antidiabético",
      "presentation": "Tabletas",
      "unit": "mg",
      "dosage": "850mg dos veces al día",
      "composition": ["Metformina clorhidrato"],
      "price": 35.0,
      "stock": 90,
      "manufacturer": "Merck",
      "expirationDate": "2026-06-10T00:00:00.000+00:00",
      "prescriptionRequired": true,
      "administrationRoute": "Oral",
      "sideEffects": ["Diarrea", "Dolor abdominal", "Náuseas"],
      "indications": ["Diabetes tipo 2"],
      "contraindications": ["Insuficiencia renal"],
      "imageUrl": "images/metformina.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Omeprazol",
      "description": "Inhibidor de la bomba de protones que reduce la cantidad de ácido en el estómago.",
      "type": "Antiácido",
      "presentation": "Cápsulas",
      "unit": "mg",
      "dosage": "20mg una vez al día",
      "composition": ["Omeprazol"],
      "price": 18.0,
      "stock": 70,
      "manufacturer": "Pfizer",
      "expirationDate": "2026-11-30T00:00:00.000+00:00",
      "prescriptionRequired": false,
      "administrationRoute": "Oral",
      "sideEffects": ["Dolor de cabeza", "Estreñimiento"],
      "indications": ["Reflujo gástrico", "Úlceras gástricas"],
      "contraindications": ["Hipersensibilidad al omeprazol"],
      "imageUrl": "images/omeprazol.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Salbutamol",
      "description": "Broncodilatador que alivia los síntomas del asma y otras enfermedades pulmonares.",
      "type": "Broncodilatador",
      "presentation": "Inhalador",
      "unit": "mcg",
      "dosage": "100mcg por inhalación",
      "composition": ["Salbutamol sulfato"],
      "price": 45.0,
      "stock": 40,
      "manufacturer": "GlaxoSmithKline",
      "expirationDate": "2026-09-25T00:00:00.000+00:00",
      "prescriptionRequired": true,
      "administrationRoute": "Inhalación",
      "sideEffects": ["Temblor", "Taquicardia"],
      "indications": ["Asma", "EPOC"],
      "contraindications": ["Arritmias cardíacas"],
      "imageUrl": "images/salbutamol.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Diclofenaco",
      "description": "Medicamento antiinflamatorio utilizado para tratar el dolor y la inflamación en diversas condiciones musculoesqueléticas.",
      "type": "Antiinflamatorio",
      "presentation": "Tabletas",
      "unit": "mg",
      "dosage": "50mg cada 8 horas",
      "composition": ["Diclofenaco sódico"],
      "price": 20.0,
      "stock": 75,
      "manufacturer": "Novartis",
      "expirationDate": "2026-10-10T00:00:00.000+00:00",
      "prescriptionRequired": true,
      "administrationRoute": "Oral",
      "sideEffects": ["Mareos", "Malestar estomacal"],
      "indications": ["Dolor muscular", "Artritis"],
      "contraindications": ["Úlceras gástricas", "Insuficiencia renal"],
      "imageUrl": "images/diclofenaco.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Clorfenamina",
      "description": "Antihistamínico que se usa para tratar los síntomas de la alergia, resfriado y fiebre del heno.",
      "type": "Antialérgico",
      "presentation": "Tabletas",
      "unit": "mg",
      "dosage": "4mg cada 6 horas",
      "composition": ["Clorfenamina maleato"],
      "price": 10.0,
      "stock": 50,
      "manufacturer": "Chinoin",
      "expirationDate": "2026-07-01T00:00:00.000+00:00",
      "prescriptionRequired": false,
      "administrationRoute": "Oral",
      "sideEffects": ["Somnolencia", "Sequedad bucal"],
      "indications": ["Rinitis alérgica", "Urticaria"],
      "contraindications": ["Glaucoma", "Hipertrofia prostática"],
      "imageUrl": "images/clorfenamina.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    },
    {
      "name": "Ketorolaco",
      "description": "Analgésico potente utilizado para el tratamiento a corto plazo del dolor moderado a severo.",
      "type": "Analgésico",
      "presentation": "Tabletas",
      "unit": "mg",
      "dosage": "10mg cada 6 horas",
      "composition": ["Ketorolaco trometamina"],
      "price": 22.0,
      "stock": 55,
      "manufacturer": "Liomont",
      "expirationDate": "2026-12-10T00:00:00.000+00:00",
      "prescriptionRequired": true,
      "administrationRoute": "Oral",
      "sideEffects": ["Dolor estomacal", "Somnolencia", "Náuseas"],
      "indications": ["Dolor postoperatorio", "Dolor dental"],
      "contraindications": ["Úlcera gástrica", "Embarazo"],
      "imageUrl": "images/ketorolaco.jpg",
      "createdAt": "2025-04-29T00:00:00.000+00:00"
    }
  ]
  